version: '3.8'

services:

  backend:
    build: ./backend
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    env_file: ./backend/.env
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend