version: '3.8'

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --root-path /api --proxy-headers --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  nginx:
    build: ./nginx
    ports:
      - "8001:8001"
      - "3000:3000"
    restart:
      always
    depends_on:
      - backend

volumes:
  caddy-data:
  caddy-config: